### ISSUE TITLE
ISO19115 compliant metadata

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/specs#86]
I've been browsing the ISO19115:2014 a bit (yeah, makes a nice bedtime reading....), looking for some new metadata members, and I realized that some of the current cityjson metadata members that are supposedly ISO19115 compliant, might not be so. I don't fully understand how this compliance works, so any help is welcome. I've skimmed [the paper](https://doi.org/10.1186/s40965-018-0057-4) too, but maybe I just didn't spot the info in there.

The cityjson metadata members that I spotted, and their equivalent in ISO19115:2014 (in my opinion):

+ datasetPointOfContact --> "pointOfContact" (in ISO19115:2014)
+ datasetTitle --> I think its "title"
+ datasetReferenceDate --> I think its "date"
+ geographicalExtent --> I think its probably "geographicExtent" or sth

The question is basically, whether this renaming breaks the compliance or not?

**Comment by liberostelios** [comment]
I am not an expert, so take everything I say with a grain of salt.

As far as I am concerned and after skimming the standard, the `pointOfContact` can be assigned to any kind of resource. In theory, a simple `pointOfContact` under metadata could just mean that this is the point of contact for the metadata. Defining that this is the point of contact for the whole dataset makes it explicit that this applies to the data itself and that it’s for the whole dataset. In some formats (e.g. geopackage) you can assign metadata to subparts of the dataset (e.g. a simple feature or a table - called data source, afair -). Therefore you could have `datasetPointOfContact` for the whole dataset and `datasourcePointOfContact` for each individual table. Remember, this is an ISO and as such it’s very messy and arbitrary therefore this can be perceived in many different ways.

I personally like plain `pointOfContact` more, but it might be that based on the ISO this is too vague because it doesn’t specify if this is for the whole dataset, the metadata itself, a data source, a feature or something. Therefore `datasetPointOfContact`, as awkward as it might sound, might be more accurate.

**Comment by balazsdukai** [comment]
My reasoining is from a technical pov

So, i have some parser that expects iso metadata, thus i code my parser to look for the exact matches of the metadata attributes. And i have the trust to code exact matching (ok, probably not case sensitive), because its a standard after all. So i assume that THE correct approach is exact matching.

Thus, if cityjson says that it has iso metadata, but then uses different names for the same attributes, then my parser won't work anymore.
Thus, iso compliance means nothing. I need to code a cityjson specific metadata parser.

Going one step further. If it is allowed to deviate from the names as prescribed by iso, eg. use `datasetPointOfContact` instead of `pointOfContact`, then what keeps us from naming the point of contact ressource `hairyPigs` for instance? 😃 Or any other arbitrary name?

**Comment by balazsdukai** [comment]
That's a good point.
What I have trouble with is that in my opinion these are all equivalent:

datasetPointOfContact --> "pointOfContact"
geographicalExtent      --> "geographicExtent"
< any misspelling >      --> ISO name

So how much "misspelling" can we allow? Because misspelling or change in the name are the same in my opinion.
